app/urls.py
# accounts/urls.py
from django.urls import path
from .views import *

app_name = 'app'



urlpatterns = [
    path('', home, name='home'),
    path('category/<int:category_id>/', category_detail, name='category_detail'),

]

menu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.utils.text import slugify
from autoslug import AutoSlugField

# Create your models here.



class SocialMedia(models.Model):
    SOCIAL_MEDIA_CHOICES = (
        ('facebook', 'Facebook'),
        ('twitter', 'Twitter'),
        ('instagram', 'Instagram'),
        ('linkedin', 'Linkedin'),
        ('youtube', 'YouTube'),
        # Diğer sosyal medya platformları ekleyebilirsiniz
    )

    name = models.CharField(max_length=20, choices=SOCIAL_MEDIA_CHOICES, unique=True, verbose_name="Adı")
    link = models.URLField(verbose_name="Bağlantı")

    class Meta:
        verbose_name = "Sosyal Medya"
        verbose_name_plural = "Sosyal Medya"

    def __str__(self):
        return self.get_name_display()
    



class Address(models.Model):
    address = models.CharField(max_length=255, null=True, blank=True)
    whatsapp_number = models.CharField(max_length=15, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        if self.address:
            return self.address
        elif self.whatsapp_number:
            return self.whatsapp_number
        elif self.phone_number:
            return self.phone_number
        return 'Adres Bilgisi Yok'
    


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name='İsim')
    slug = AutoSlugField(populate_from='name', unique=True, verbose_name="Slug")
    description = models.TextField(blank=True, null=True, verbose_name='Açıklama')
    image = models.ImageField(upload_to='categories/', blank=True, null=True, verbose_name='Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Product(models.Model):
    CURRENCY_CHOICES = [
        ('EUR', 'Euro (€)'),
        ('USD', 'US Doları ($)'),
        ('TRY', 'Türk Lirası (₺)'),
        # Diğer para birimleri eklenebilir
    ]

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Kategori')
    name = models.CharField(max_length=250, verbose_name='İsim')
    slug = AutoSlugField(populate_from='name', unique=True, verbose_name="Slug")
    ingredients = models.TextField(blank=True, null=True, verbose_name='İçindekiler')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Fiyat')
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='EUR', verbose_name='Para Birimi')
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name='Resim')
    available = models.BooleanField(default=True, verbose_name='Mevcut')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_currency_symbol(self):
        symbols = {
            'EUR': '€',
            'USD': '$',
            'TRY': '₺',
            # Diğer para birimi sembolleri eklenebilir
        }
        return symbols.get(self.currency, '')

    def display_price(self):
        return f"{self.get_currency_symbol()}{self.price}"
    display_price.short_description = 'Fiyat'

app/views.py
from django.shortcuts import render,get_object_or_404
from .models import *
# Create your views here.


def mainContext():
    # Address ve SocialMedia verilerini al
    address = Address.objects.first()
    social_media_links = SocialMedia.objects.all()
    
    # Template'e veri geçirme
    context = {
        'address': address,
        'social_media_links': social_media_links,
    }
    return context




def home(request):
    categories = Category.objects.all() 

    context_data = mainContext()

    context = {
        "categories":categories,
    }

    context_data.update(context)

    return render(request, 'core/home.html', context_data)




def category_detail(request, category_id):
    context_data = mainContext()
    category = get_object_or_404(Category, id=category_id)
    
    products = Product.objects.filter(category=category, available=True)
    
    context = {
        'category': category,
        'products': products,
    }
    
    context.update(context_data)
    return render(request, 'core/category_detail.html', context)

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title>08 Kebap</title>


    <meta name="google" content="notranslate">
    <meta name="description"
        content="08 Kebap">

        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var canonicalLink = document.createElement('link');
                canonicalLink.rel = 'canonical';
                canonicalLink.href = window.location.href;
    
                document.head.appendChild(canonicalLink);
            });
        </script>    
        <meta name="robots" content="index,follow">


    <link rel="stylesheet" type="text/css" href="{% static 'css/F708B742B0A99F864.css' %}" />

    <link href="{% static 'css/dmenu10f0.css' %}" rel="stylesheet" />
    <style>
        :root {
            --ui-font-set: BlinkMacSystemFont, -apple-system, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
            --primary-font-set: "Archer A", "Archer B", serif;
            --secondary-font-set: "Archer A", "Archer B", serif;
            --dm-heading1-fontfamily: var(--primary-font-set);
            --dm-heading1-fontsize: 1.4rem;
            --dm-heading1-fontweight: 800;
            --dm-heading1-tracking: -0.013rem;
            --dm-heading1-texttransform: uppercase;
            --dm-sp-sectiontitle-fontsize: 1.6rem;
            --dm-heading2-fontfamily: var(--primary-font-set);
            --dm-heading2-fontsize: 1.4rem;
            --dm-heading2-fontweight: 800;
            --dm-heading2-tracking: -0.013rem;
            --dm-heading2-texttransform: uppercase;
            --dm-menusection-fontfamily: var(--primary-font-set);
            --dm-menusection-fontsize: 1.8rem;
            --dm-menusection-fontweight: 700;
            --dm-menusection-tracking: -0.013rem;
            --dm-menusection-texttransform: uppercase;
            --dm-menubundletitle-fontsize: 1.4rem;
            --dm-menubundletitle-fontfamily: var(--primary-font-set);
            --dm-menubundletitle-fontweight: 500;
            --dm-pagetitle-fontfamily: var(--primary-font-set);
            --dm-pagetitle-fontsize: 2.2rem;
            --dm-pagetitle-fontweight: 800;
            --dm-pagetitle-tracking: var(--dm-heading1-tracking);
            --dm-tag-fontfamily: var(--ui-font-set);
            --dm-tag-fontweight: 500;
            --dm-tag-fontsize: 0.8rem;
            --dm-btnorder-fontsize: 0.7rem;
            --dm-btnorder-fontweight: 800;
            --dm-btnorder-texttransform: uppercase;
            --dm-announcement-title-fontsize: 1.2rem;
            --dm-announcement-p-fontsize: 1rem;
            --dm-announcement-p-fontfamily: var(--primary-font-set);
            --dm-announcement-p-fontweight: 500;
            --dm-fontsize-xl: 2rem;
            --dm-fontsize-lg: 1.7rem;
            --dm-fontsize-m: 1.65rem;
            --dm-fontsize-r: 1.5rem;
            --dm-fontsize-s: 1.2rem;
            --dm-fontsize-xs: 1rem;
            --dm-fontsize-xxs: 0.7rem;
            --dm-letterspacing-snug: 0rem;
            --dm-rounded-xs: 2px;
            --dm-rounded-s: 3px;
            --dm-rounded-r: 6px;
            --dm-rounded-full: 1242px;
            --dm-itembox-mb: 24px;
            --dm-itembox-title-fontfamily: var(--primary-font-set);
            --dm-itembox-title-fontsize: 1.2rem;
            --dm-itembox-title-fontweight: 800;
            --dm-itembox-title-tracking: -0.01rem;
            --dm-itembox-title-texttransform: inherit;
            --dm-itembox-titlefeatured-fontsize: 1.5rem;
            --dm-itembox-p-fontfamily: var(--primary-font-set);
            --dm-itembox-p-fontsize: 1rem;
            --dm-itembox-p-fontweight: 500;
            --dm-itembox-p-lineheight: 140%;
            --dm-itembox-variation-fontfamily: var(--primary-font-set);
            --dm-itembox-variation-fontweight: var(--dm-itembox-title-fontweight);
            --dm-itembox-variation-fontsize: var(--dm-fontsize-xs);
            --dm-itembox-price-fontfamily: var(--primary-font-set);
            --dmst-gul: inherit;
        }

        :root {
            --dm-bgcolor: #faeee0;
            --dm-sidebar-bg: linear-gradient(180deg, #434343, #000);
            --dm-color: #562400;
            --dm-link-color: #3498db;
            --dm-bg-gradient: #3e1e07;
            --dm-text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.6), 1px 1px 8px rgba(0, 0, 0, 0.9);
            --dm-sticky-header-color: rgba(60, 30, 20, 0.3);
            --dm-shadowglass: rgba(0, 0, 0, 0.3);
            --dm-heading1-color: #562400;
            --dm-heading2-color: #562400;
            --dm-menusection-color: #fff;
            --dm-promobadge-bgcolor: rgba(254, 243, 199, 1);
            --dm-promobadge-color: rgba(180, 83, 9, 1);
            --dm-tag-s1-bgcolor: #ff6b81;
            --dm-tag-s1-color: #FFFFFF;
            --dm-tag-s2-bgcolor: #1e90ff;
            --dm-tag-s2-color: #FFFFFF;
            --dm-tag-s3-bgcolor: #1abc9c;
            --dm-tag-s3-color: #FFFFFF;
            --dm-tag-s4-bgcolor: #8e44ad;
            --dm-tag-s4-color: #FFFFFF;
            --dm-tag-s5-bgcolor: #e67e22;
            --dm-tag-s5-color: #FFFFFF;
            --dm-tag-s6-bgcolor: #34495e;
            --dm-tag-s6-color: #FFFFFF;
            --dm-btnadd-bgcolor: #562400;
            --dm-btnadd-color: #ffffff;
            --dm-btnorder-bgcolor: #e67e22;
            --dm-btnorder-color: #ffffff;
            --dm-announcement-bgcolor: #fff;
            --dm-announcement-title-color: var(--dm-heading1-color);
            --dm-action-navigate-color: #FFC312;
            --dm-action-call-color: #00a8ff;
            --dm-action-share-color: #ED4C67;
            --dm-shadow-action: none;
            --dm-itembox-title-color: #e67e22;
            --dm-itembox-p-color: inherit;
            --dm-order-btnorder-whatsapp-bgcolor: #34bf49;
            --dm-itembox-featured-bgcolor: #3e1e07;
            --dm-itembox-titlefeatured-color: #e67e22;
            --dm-itembox-pfeatured-color: #ffffff;
            --dm-footerinstagram-color: var(--dm-color);
            --dm-footertwitter-color: var(--dm-color);
            --dm-footerfacebook-color: var(--dm-color);
            --dm-footeryoutube-color: var(--dm-color);
            --dm-footerfoursquare-color: var(--dm-color);
            --dm-footertripadvisor-color: var(--dm-color);
            --dm-relatedbox-bgcolor: #e9b6a9;
            --dm-order-nocart-color: #a0144b;
            --dmst-yıldırım: inherit;
        }
    </style>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
    <style>
        .swiper {
            display: none;
        }

        .close-btn {
            display: block;
            position: absolute;
            right: 0;
            width: 48px;
            height: 48px;
            background-color: transparent;
            z-index: 1000;
        }

        .arrow {
            position: absolute;
            height: 3px;
            width: 25px;
            background-color: rgba(255, 255, 255, 1);
            top: 24px;
            left: 11px;
        }

        .a1 {
            transform: rotate(45deg);
        }

        .a2 {
            transform: rotate(-45deg);
        }

        .swiper.is-active {
            display: block;
            position: fixed;
            left: 0;
            right: 0;
            bottom: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(15, 23, 42, 0.9);
            z-index: 1000000;
        }

        .swiper-pagination {
            position: relative;
            margin-top: 10px;
        }
    </style>
    <style>
        .termsfeed-com---palette-light.termsfeed-com---nb {
            background-color: #d6d9e6 !important;
        }

        .termsfeed-com---palette-light .cc-nb-okagree {
            background-color: #2d83c4 !important;
        }

        .termsfeed-com---nb .cc-nb-main-container {
            padding: 0.8rem !important;
        }

        .termsfeed-com---nb .cc-nb-title {
            font-size: 13px !important;
        }

        .termsfeed-com---nb .cc-nb-text {
            font-size: 10px !important;
            margin: 0 0 0.4rem 0 !important;
        }

        .termsfeed-com---reset p {
            margin-bottom: 0.2rem !important;
        }
    </style>
</head>

<body class="view-menu">
    
    {% block content %}

    {% endblock content %}

    <script src="{% static 'js/dmenu-visitor-qrmenu34f1.js' %}"></script>

    
</body>


</html>

templates/core/category_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} {{ category.name }} {% endblock title %}

{% block content %}


<div class="sidepage-hero"
{% if category.image %}
style="background-image: url({{ category.image.url }});"
{% endif %}>
        <div class="dmu_dark-overlay"></div> <a href="index.html" class="sidepage-hero__link">
            <img class="sidepage-hero__logo--s"
                src="{% static 'img/logo.png' %}">
        </a>
        <h1 class="sidepage-hero__title"> {{ category.name }}</h1>
        <a class="sidepage-hero__btn" href="{% url 'app:home' %}">
            Zurück zum Menü
        </a>

       
    </div>




    <div class="items-container ">
        <h3 class="section-subtitle" style="position:sticky;">{{ category.name }}</h3>
        <p class="section-subtitle-description"></p>
        {% for product in products %}
        <div id="i-{{ product.id }}" class="item-box item-box-image">
            {% if product.image %}
                <img class="item-image swiper-thumb"
                     src="{{ product.image.url }}"
                     alt="{{ product.name }}"
                     data-title="{{ product.name }}"
                     data-desc="{{ product.ingredients }}"
                     data-image="{{ product.image.url }}">
            {% endif %}
            <div class="item-content">
                <div class="primary-content">
                    <div class="primary-head">
                        <div class="primary-headtext">
                            <h4 class="primary-title w-image">
                                {{ product.name }}
                            </h4>
                        </div>
                        <div class="dots"></div>
                        <div class="price-box">
                            <div class="price-content --item">
                                <div class="price">
                                    {{ product.display_price }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <p>{{ product.ingredients }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    

    </div>


{% include 'core/telephone.html' %}

{% include 'core/footer.html' %}
{% endblock %}

templates/core/footer.html
{% load static %}
{% block content %}


<footer>
    <div class="social-footer">
        {% for social in social_media_links %}
            <a class="social-footer-item {{ social.name }}" href="{{ social.link }}" target="_blank">
                {% if social.name == "facebook" %}
                    <i class="fab fa-2x fa-facebook"></i>
                {% elif social.name == "twitter" %}
                    <i class="fab fa-2x fa-twitter"></i>
                {% elif social.name == "instagram" %}
                    <i class="fab fa-2x fa-instagram"></i>
                {% elif social.name == "linkedin" %}
                    <i class="fab fa-2x fa-linkedin"></i>
                {% elif social.name == "youtube" %}
                    <i class="fab fa-2x fa-youtube"></i>
                {% else %}
                    <i class="fab fa-2x fa-{{ social.name }}"></i>
                {% endif %}
            </a>
        {% endfor %}
    </div>
    <strong class="footer-company-name">08 Kebab</strong><br>
    {% if address %}
        <p class="footer-company-address">{% if address.address %}
            {{ address.address }}<br>
        {% endif %}<br>
            {% if address.phone_number %}
                <a href="tel:{{ address.phone_number }}" class="text-link">{{ address.phone_number }}</a><br>
            {% endif %}
         
        </p>
    {% endif %}
</footer>

{% endblock %}

templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}  {% endblock title %}

{% block content %}





<div class="sidepage-hero"
    style="background-image: url('../assets.dijital.menu/photos/2jtXo5bNftnpxx16/hero/menu/8b7fc403dd11e5989da39695624f82a1.jpg')">

    <a href="index.html">
        <img class="sidepage-hero__logo--l"
            src="{% static 'img/logo.png' %}"
            alt="Murad&#039;s Cuisine Logosu">
    </a>


</div>



<div class="sections-content">
    <div id="menu-content" class="menu-grid">
        
        {% for category in categories %}
    <a class="menu-grid-item style-4" href="{% url 'app:category_detail' category.id %}"
        style="{% if category.image %}background-image: url({{ category.image.url }});{% endif %}">
        <div class="black-box"></div>
        <span class="text-box">{{ category.name }}</span>
    </a>
{% empty %}
    <p>No categories available.</p>
{% endfor %}
        
    </div>
</div>





{% include 'core/telephone.html' %}

{% include 'core/footer.html' %}
{% endblock %}

templates/core/telephone.html
{% load static %}
{% block content %}

<style>
    /* Arama butonu CSS kodlarını kendinize göre düzenleyebilirsiniz */
    .telefon-ara-btn {
        color: white;
        background: #2c8a00;
        font-size: 24px;
        padding: 3px 11px 3px;
        text-decoration: none;
        font-family: Nunito;
        border-radius: 5px;
        font-weight: 600;
        position: fixed;
        bottom: 20px; /* Sayfanın alt kısmında */
        right: 20px; /* Sayfanın sağında */
        transform: translateY(-50%);
        z-index: 9999;
    }

    .telefon-ara-btn:hover {
        padding: 4px 12px 4px;
        transition: 0.5s;
        background: #35a800;
    }

    .whatsapp-btn {
        color: white;
        background: #25D366; /* WhatsApp yeşili */
        font-size: 24px;
        padding: 3px 11px 3px;
        text-decoration: none;
        font-family: Nunito;
        border-radius: 5px;
        font-weight: 600;
        position: fixed;
        bottom: 20px; /* Sayfanın alt kısmında */
        left: 20px; /* Sayfanın solunda */
        transform: translateY(-50%);
        z-index: 9999;
    }

    .whatsapp-btn:hover {
        padding: 4px 12px 4px;
        transition: 0.5s;
        background: #128C7E; /* WhatsApp yeşilinin koyu tonu */
    }
</style>


{% if address %}
    {% if address.whatsapp_number %}
        <a class="whatsapp-btn" href="https://wa.me/{{ address.whatsapp_number }}" target="_blank">
            <i class="fab fa-whatsapp" aria-hidden="true"></i>
        </a>
    {% endif %}
    {% if address.phone_number %}
        <a class="telefon-ara-btn" href="tel:{{ address.phone_number }}">
            <i class="fa fa-phone" aria-hidden="true"></i>
        </a>
    {% endif %}
{% endif %}

{% endblock %}